version: '3.9'

networks:
  internal_network:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - 5432:5432
    networks:
      internal_network:
        ipv4_address: "172.20.0.3"
    volumes:
      - ./postgres-db/init.sql:/docker-entrypoint-initdb.d/init.sql

  server1:
    build: .
    image: server
    tty: true
    ports:
      - 8080:8080
    networks:
      internal_network:
        ipv4_address: "172.20.0.4"
    environment:
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_NAME=database
      - DB_HOST=db
      - DB_PORT=5432
      - SERVER_IP_ADDR=172.20.0.4
      - SERVER_PORT=8080
    depends_on:
      - db
    restart: always

  server2:
    build: .
    image: server
    tty: true
    ports:
      - 8081:8081
    networks:
      internal_network:
        ipv4_address: "172.20.0.5"
    environment:
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_NAME=database
      - DB_HOST=db
      - DB_PORT=5432
      - SERVER_IP_ADDR=172.20.0.5
      - SERVER_PORT=8081
    depends_on:
      - db
    restart: always
