version: '3.9'

services:
  server:
    build: .
    image: server
    tty: true
    ports:
      - 8080:8080
    environment:
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_NAME=database
      - DB_HOST=db
      - DB_PORT=5432
      - MY_PORT=8080
    depends_on:
      - db
    restart: always
    volumes:
      - ./message-dump/message_dump.txt:/server/message_dump.txt

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - 5432:5432
    volumes:
      - ./postgres-db/init.sql:/docker-entrypoint-initdb.d/init.sql
